#
# Module manifest for module 'sqldsc'
#
# Generated by: Christian Duque
#
# Generated on: 13/04/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'sqldsc.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a7fedd92-7057-4ff4-b162-d64067da2724'

# Author of this module
Author = 'Christian Duque'

# Copyright statement for this module
Copyright = '(c) 2020 Christian Duque. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This will be a for SQL DBA'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    #  @{ ModuleName = 'SqlServer'; ModuleVersion = '21.1.18121'; } use this template if specifying specific version
    @{ ModuleName = 'sqlserverdsc'; ModuleVersion = '17.0.0'; }
    #dbatools
    #ReportingServicesTools
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
#FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
#CmdletsToExport = @()

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
#AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}